# Generated by Django 4.1.5 on 2023-01-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecs',
            options={'verbose_name': 'Ecs', 'verbose_name_plural': 'Ecs'},
        ),
    ]
