# Generated by Django 4.1.5 on 2023-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0003_slb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slb',
            name='SLBAlgorithm',
            field=models.CharField(max_length=255),
        ),
    ]
