# Generated by Django 4.1.5 on 2023-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0004_alter_slb_slbalgorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slb',
            name='Lastseen',
            field=models.DateTimeField(),
        ),
    ]
