# Generated by Django 4.1.5 on 2023-01-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0006_alter_ecs_lastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='rds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDSId', models.CharField(max_length=255)),
                ('RDSIp', models.CharField(max_length=255)),
                ('RDSPort', models.IntegerField()),
                ('RDSCpu', models.IntegerField()),
                ('RDSMemory', models.IntegerField()),
                ('RDSIOPS', models.IntegerField()),
                ('RDSMaxConnection', models.IntegerField()),
                ('RDSEngine', models.CharField(max_length=255)),
                ('RDSInstanceType', models.CharField(max_length=255)),
                ('RDSVSwitch', models.CharField(max_length=255)),
                ('RDSStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
