# Generated by Django 4.1.5 on 2023-01-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0007_rds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rds',
            options={'verbose_name': 'Rds', 'verbose_name_plural': 'Rds'},
        ),
    ]
