# Generated by Django 4.1.5 on 2023-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0008_alter_rds_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='RDSFlorian',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
